/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fMJ3WqQYx6N
 */
import Link from "next/link"
import { Card } from "@/components/ui/card"

export function Landing({ children }) {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div
          className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <Card>
            <div className="p-4">
              {children}
            </div>
          </Card>
        </div>
      </div>
    </section>)
  );
}
